
on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master 

        - name: 'Setup Node version'
          uses: actions/setup-node@v3
          with:
            node-version: 18.12.0 
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - uses: azure/docker-login@v1
          with:
            login-server: abbynav.azurecr.io
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t abbynav.azurecr.io/flickerapp:${{ github.sha }}
            docker push abbynav.azurecr.io/flickerapp:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: myResourceGroup
            dns-name-label: abbynav-demo
            image: abbynav.azurecr.io/flickerapp:${{ github.sha }}
            cpu: 1   #Optional
            memory: 1.5   #Optional
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            ports: 3002
            name: abbynav-container
            secure-environment-variables: FLICKR_API_KEY=${{ secrets.FLICKR_API_KEY }}
            location: 'australiaeast'